spring:
  application:
    name: student-data-processor

  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

# File paths configuration
app:
  file:
    excel-output-path: "C:/var/log/applications/API/dataprocessing/"
    csv-output-path: "C:/var/log/applications/API/dataprocessing/"

logging:
  level:
    org.springframework: INFO
    com.example.studentprocessor: DEBUG